# Reading and writing

As mentioned in the previous chapter, there are multiple libraries for reading and writing medical images. We will use ants because it is fast and allows for seamless interaction with numpy and tensor libraries like pytorch. 

This chapter will teach you how to read images from file or create them from arrays. You will learn the basics about how medical images are typically structured. What may surprise you is that medical images are not just dumb arrays. They have important metadata associated with them -- for example, orientation, spacing, and direction -- that helps you know more about the images.

Besides reading images, you will also learn how to save images. This is important because you will need to save images that you predict from your model or that you transform during processing steps.

## Loading from file

Reading an image from file is simple with ants, as all you need is the `image_read` function.

In [1]:
import ants
filepath = ants.get_data('r16') # get path to an image included in ants
img = ants.image_read(filepath)

Once you've read in an image, you can print out the image to the console to see important information about the image's data and structure.

In [2]:
print(img)

ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (256, 256)
	 Spacing    : (1.0, 1.0)
	 Origin     : (0.0, 0.0)
	 Direction  : [1. 0. 0. 1.]



Notice how there is more than just the dimension and datatype of the image as you would see in a standard numpy array. We also have spacing, origin, and direction. This information tells you a lot about the image and is important for many image processing tasks.

## Converting to numpy

Images from ants interoperate closely with numpy. Although the underlying data is not stored in numpy, it is easy to convert ants images to numpy arrays:

In [3]:
arr = img.numpy()
print(arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Notice that you see a lot of zeros in the array. Lots of "blank" space around the edges is a common feature of medical images that you will learn to handle in future chapters. 

The relationship with numpy goes the other way, as well. You can easily create an ants image from a numpy array.

In [4]:
import numpy as np
arr = np.random.randn(128,128)
img = ants.from_numpy(arr)
print(img)

ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (128, 128)
	 Spacing    : (1.0, 1.0)
	 Origin     : (0.0, 0.0)
	 Direction  : [1. 0. 0. 1.]



## Writing images to file

When you want to save an image to file, you can use the `image_write` function in ants to do so. All common formats such as dicom and others are supported. Since we are using brain images in this example, we will use nifti.

In [8]:
from tempfile import NamedTemporaryFile
filepath = NamedTemporaryFile(suffix='.nii.gz')
ants.image_write(img, filepath.name)

## Summary

In this chapter, you learned how to read images from file using the ants library. Ants is fast and flexible when it comes to reading medical images. It also works well with numpy and other tensor libraries, as we showed here. Moreover, you learned how to save images to file. This will be useful when you want to save results down the line.